---

- name: Update to latest patch level
  shell: freebsd-update fetch --not-running-from-cron && freebsd-update install

- name: Install required packages
  shell: pkg install -y go gmake git-lite bash curl tmux sudo

- name: Set hostname 1/2 - hostname
  shell: "hostname {{ lookup('env','PACKER_TEMPLATE') | regex_replace('[^a-zA-Z0-9-]', '-') }}.build.prometheus.io"

- lineinfile:
    dest: /etc/rc.conf
    create: yes
    owner: root
    group: wheel
    mode: 664
    regexp: '^hostname'
    line: "hostname=\"{{ lookup('env','PACKER_TEMPLATE') | regex_replace('[^a-zA-Z0-9-]', '-') }}.build.prometheus.io\""

# configure bash
- lineinfile:
    dest: /etc/fstab
    create: yes
    owner: root
    group: wheel
    mode: 664
    regexp: '^fdesc'
    line: 'fdesc /dev/fd fdescfs rw 0 0'

- name: Mount fdesc filesystem
  shell: mount /dev/fd

# configure sudo
- name: Configure sudo
  copy:
    src: sudoers.d/default
    dest: "{{ sudoersd_path }}"
    owner: root
    group: wheel
    mode: 644
