---

- name: Symlink bash to /bin/bash for compatibility
  file:
    src: "{{ bash_prefix }}"
    dest: "/bin/bash"
    owner: root
    group: wheel
    state: link
    force: no

- name: Install buildkite agent
  shell: "sudo -u peon sh -c 'export TOKEN={{ lookup('env','BUILDKITE_TOKEN') }}; curl -sL https://raw.githubusercontent.com/buildkite/agent/master/install.sh | bash'"

- lineinfile:
    dest: /etc/rc.local
    create: yes
    owner: root
    group: wheel
    mode: 664
    regexp: 'buildkite-agent'
    line: "/usr/local/bin/sudo -u peon sh -c 'tmux new -d -s buildkite-agent \"while sleep 1; do ~/.buildkite-agent/bin/buildkite-agent start; done\"'"

