- name: Add peon group
  group:
    name: peon
    state: present

- name: Add peon user
  user:
    name: peon
    group: peon
    comment: "Peon Worker"
    shell: "{{ bash_prefix }}/bin/bash"

- name: "peon: add ~/bin"
  file:
    path: /home/peon/bin
    state: directory
    owner: peon
    group: peon
    mode: 0755

- name: "peon: add ~/go"
  file:
    path: /home/peon/go
    state: directory
    owner: peon
    group: peon
    mode: 0755

- name: "peon: configure GOPATH"
  lineinfile:
    dest: /home/peon/.bashrc
    create: yes
    owner: peon
    group: peon
    mode: 664
    regexp: '^export GOPATH='
    line: 'export GOPATH="$HOME/go"'

